/* ALERT */
export const SET_ALERT = 'SET_ALERT'
export const SET_ALERT_SUCCESS = 'SET_ALERT_SUCCESS'
export const REMOVE_ALERT_SUCCESS = 'REMOVE_ALERT_SUCCESS'
export const CLOSE_ALERT = 'CLOSE_ALERT'
export const CLOSE_ALERT_SUCCESS = 'CLOSE_ALERT_SUCCESS'
