export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT'
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE'

export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const CLEAN_UP_LOGIN_USER = 'CLEAN_UP_LOGIN_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT'
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS'
export const VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED'

export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS'
export const ACTIVATE_ACCOUNT_FAILED = 'ACTIVATE_ACCOUNT_FAILED'

export const ADMIN_ACTIVATE_ACCOUNT = 'ADMIN_ACTIVATE_ACCOUNT'
export const ADMIN_ACTIVATE_ACCOUNT_SUCCESS = 'ADMIN_ACTIVATE_ACCOUNT_SUCCESS'
export const ADMIN_ACTIVATE_ACCOUNT_FAILED = 'ADMIN_ACTIVATE_ACCOUNT_FAILED'

export const COLLECT_USER_MAIL = 'COLLECT_USER_MAIL'
export const COLLECT_USER_MAIL_SUCCESS = 'COLLECT_USER_MAIL_SUCCESS'
export const COLLECT_USER_MAIL_FAILED = 'COLLECT_USER_MAIL_FAILED'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const INITIATE_LOGOUT_USER = 'INITIATE_LOGOUT_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
