export const GET_JOBS_LIST = 'GET_JOBS_LIST'
export const GET_JOBS_LIST_SUCCESS = 'GET_JOBS_LIST_SUCCESS'
export const GET_JOBS_LIST_FAILED = 'GET_JOBS_LIST_FAILED'

export const GET_JOB_DETAILS = 'GET_JOB_DETAILS'
export const GET_JOB_DETAILS_SUCCESS = 'GET_JOB_DETAILS_SUCCESS'
export const GET_JOB_DETAILS_FAILED = 'GET_JOB_DETAILS_FAILED'

export const APPLY_JOB = 'APPLY_JOB'
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS'
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED'

export const FETCH_JOB_FORM = 'FETCH_JOB_FORM'
export const FETCH_JOB_FORM_SUCCESS = 'FETCH_JOB_FORM_SUCCESS'
export const FETCH_JOB_FORM_FAILED = 'FETCH_JOB_FORM_FAILED'
